version: '3.1'
services:
  stats-server:
    build: stat/
    image: ewm-stat
    container_name: ewm-stat-dock
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stat-db-dock
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build: main/
    image: ewm-main
    container_name: ewm-main-dock
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - EWM-STAT_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db-dock
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm