CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(255)                            NOT NULL,
    uri       VARCHAR(512)                            NOT NULL,
    ip        VARCHAR(512)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS mails
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    receiver_email    VARCHAR(255)                            NOT NULL,
    receiver_name     VARCHAR(255)                            NOT NULL,
    event_title       VARCHAR(255)                            NOT NULL,
    event_location    VARCHAR(255)                            NOT NULL,
    event_distance    FLOAT                                   NOT NULL,
    event_lat         FLOAT                                   NOT NULL,
    event_lon         FLOAT                                   NOT NULL,
    event_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    sent_timestamp    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_mails PRIMARY KEY (id),
    CONSTRAINT uq_email_title_lat_lon UNIQUE (receiver_email, event_title, event_lat, event_lon)
);